print("Welcome to the tip calculator")
total_bill = float(input("What was the total bill? $"))
percentage = float(input("What percentage tip would you like to give? 10, 12, or, 15) "))
split = int(input("How many people to splt the bill? "))
print("Each person should pay: $", round((total_bill * ((percentage / 100) + 1)) / split, 2))
